=== vallabkaranam/toon-json-benchmark/data/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "service": {
      "type": "string"
    },
    "env": {
      "type": "string",
      "enum": [
        "prod",
        "staging",
        "dev"
      ]
    },
    "type": {
      "type": "string",
      "enum": [
        "auth",
        "payment",
        "system",
        "network",
        "job"
      ]
    },
    "status": {
      "type": "string",
      "enum": [
        "success",
        "failed",
        "warning"
      ]
    },
    "severity": {
      "type": "integer",
      "minimum": 1,
      "maximum": 5
    },
    "source": {
      "type": "string"
    },
    "metadata": {
      "type": "object",
      "properties": {
        "request_id": {
          "type": "string"
        },
        "user_id": {
          "type": "string"
        },
        "region": {
          "type": "string"
        },
        "retry_count": {
          "type": "integer"
        },
        "latency_ms": {
          "type": "number"
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "request_id",
        "user_id",
        "region",
        "retry_count",
        "latency_ms",
        "tags"
      ]
    },
    "message": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "timestamp",
    "service",
    "env",
    "type",
    "status",
    "severity",
    "source",
    "metadata",
    "message"
  ]
}

=== vallabkaranam/toon-json-benchmark/data/events.json
[
  {
    "id": "c9e48e8c-25c6-4c45-863d-04ee541c7a86",
    "timestamp": "2025-12-20T16:19:18.312720+00:00",
    "service": "data-pipeline",
    "env": "prod",
    "type": "payment",
    "status": "failed",
    "severity": 3,
    "source": "us-west-2/instance-9850",
    "metadata": {
      "request_id": "req-402adf9c",
      "user_id": "usr-3858",
      "region": "us-east-1",
      "retry_count": 5,
      "latency_ms": 4333.57,
      "tags": [
        "payment"
      ]
    },
    "message": "Operation completed for prod environment."
  },
  {
    "id": "0c6b7074-ab10-4c9b-9168-2e09f1f7d904",
    "timestamp": "2025-12-20T17:21:18.314229+00:00",
    "service": "web-server",
    "env": "dev",
    "type": "payment",
    "status": "warning",
    "severity": 3,
    "source": "us-west-2/instance-2113",
    "metadata": {
      "request_id": "req-b509109b",
      "user_id": "usr-3474",
      "region": "us-east-1",
      "retry_count": 0,
      "latency_ms": 1101.41,
      "tags": []
    },
    "message": "Operation failed for dev environment."
  },
  {
    "id": "0e0630cd-996d-4c50-bc04-a168652ffb49",
    "timestamp": "2025-12-20T17:44:05.312856+00:00",
    "service": "payment-service",
    "env": "prod",
    "type": "system",
    "status": "failed",
    "severity": 3,
    "source": "us-west-2/instance-3248",
    "metadata": {
      "request_id": "req-c3a00c6f",
      "user_id": "usr-5186",
      "region": "eu-central-1",
      "retry_count": 2,
      "latency_ms": 608.72,
      "tags": [
        "auth",
        "payment"
      ]
    },
    "message": "Operation failed for prod environment."
  },
  {
    "id": "b3957a98-2320-4ff5-b538-f96c033e02f7",
    "timestamp": "2025-12-20T18:48:06.314740+00:00",
    "service": "payment-service",
    "env": "prod",
    "type": "network",
    "status": "success",
    "severity": 4,
    "source": "eu-central-1/instance-9568",
    "metadata": {
      "request_id": "req-8468b74d",
      "user_id": "usr-5247",
      "region": "us-west-2",
      "retry_count": 0,
      "latency_ms": 1865.63,
      "tags": [
        "auth"
      ]
    },
    "message": "Operation retrying for prod environment."
  },
  {
    "id": "694d7b00-8d38-4327-883f-13c601b158e9",
    "timestamp": "2025-12-20T18:56:51.314243+00:00",
    "service": "auth-service",
    "env": "prod",
    "type": "job",
    "status": "failed",
    "severity": 4,
    "source": "eu-central-1/instance-9777",
    "metadata": {
      "request_id": "req-fa3c1628",
      "user_id": "usr-5697",
      "region": "us-east-1",
      "retry_count": 4,
      "latency_ms": 4067.65,
      "tags": [
        "auth",
        "critical",
        "edge"
      ]
    },
    "message": "Operation retrying for prod environment."
  },
  {
    "id": "8d03c91e-4f8d-4238-a88b-78b5b5b453ca",
    "timestamp": "2025-12-20T19:28:43.312512+00:00",
    "service": "notification-service",
    "env": "prod",
    "type": "network",
    "status": "success",
    "severity": 4,
    "source": "us-east-1/instance-4681",
    "metadata": {
      "request_id": "req-fe049059",
      "user_id": "usr-2858",
      "region": "ap-northeast-1",
      "retry_count": 0,
      "latency_ms": 4735.83,
      "tags": [
        "auth",
        "critical",
        "payment"
      ]
    },
    "message": "Operation retrying for prod environment."
  },
  {
    "id": "4b7f2183-088d-4d82-9883-e3f8cc9803de",
    "timestamp": "2025-12-20T21:20:38.315025+00:00",
    "service": "data-pipeline",
    "env": "prod",
    "type": "system",
    "status": "failed",
    "severity": 2,
    "source": "us-east-1/instance-2215",
    "metadata": {
      "request_id": "req-5780be17",
      "user_id": "usr-3787",
      "region": "ap-northeast-1",
      "retry_count": 1,
      "latency_ms": 3662.61,
      "tags": []
    },
    "message": "Operation retrying for prod environment."
  },
  {
    "id": "a65f7b8a-dbb4-4021-bdde-64afa75b395a",
    "timestamp": "2025-12-21T00:43:28.314270+00:00",
    "service": "auth-service",
    "env": "dev",
    "type": "network",
    "status": "success",
    "severity": 4,
    "source": "ap-northeast-1/instance-7179",
    "metadata": {
      "request_id": "req-8d7dd772",
      "user_id": "usr-8798",
      "region": "us-east-1",
      "retry_count": 0,
      "latency_ms": 3187.37,
      "tags": []
    },
    "message": "Operation retrying for dev environment."
  },
  {
    "id": "6511e61a-1436-45f5-8c81-926079ec533c",
    "timestamp": "2025-12-21T01:36:40.315094+00:00",
    "service": "notification-service",
    "env": "prod",
    "type": "job",
    "status": "success",
    "severity": 3,
    "source": "us-west-2/instance-2970",
    "metadata": {
      "request_id": "req-f3025d16",
      "user_id": "usr-8357",
      "region": "us-west-2",
      "retry_count": 0,
      "latency_ms": 4745.82,
      "tags": [
        "batch",
        "edge",
        "payment"
      ]
    },
    "message": "Operation completed for prod environment."
  },
  {
    "id": "ef158d5b-2d00-4d05-966d-4627e1dace6a",
    "timestamp": "2025-12-21T02:04:50.313981+00:00",
    "service": "web-server",
    "env": "staging",
    "type": "network",
    "status": "warning",
    "severity": 1,
    "source": "us-west-2/instance-5742",
    "metadata": {
      "request_id": "req-e0723d96",
      "user_id": "usr-1613",
      "region": "us-east-1",
      "retry_count": 0,
      "latency_ms": 1498.98,
      "tags": [
        "edge"
      ]
    },
    "message": "Operation retrying for staging environment."
  },
  {
    "id": "f23e323d-0b9b-4934-a3c8-6d301dde7969",
    "timestamp": "2025-12-21T02:20:04.312679+00:00",
    "service": "data-pipeline",
    "env": "prod",
    "type": "network",
    "status": "failed",
    "severity": 3,
    "source": "us-east-1/instance-2592",
    "metadata": {
      "request_id": "req-3c1bdacc",
      "user_id": "usr-9807",
      "region": "us-west-2",
      "retry_count": 3,
      "latency_ms": 2273.68,
      "tags": [
        "critical",
        "edge",
        "infra"
      ]
    },
    "message": "Operation retrying for prod environment."
  },
  {
    "id": "9adf4709-ac75-4344-a08e-149e44b9e602",
    "timestamp": "2025-12-21T03:00:53.314173+00:00",
    "service": "auth-service",
    "env": "staging",
    "type": "payment",
    "status": "success",
    "severity": 4,
    "source": "us-west-2/instance-8854",
    "metadata": {
      "request_id": "req-3579c143",
      "user_id": "usr-6455",
      "region": "eu-central-1",
      "retry_count": 0,
      "latency_ms": 4785.53,
      "tags": [
        "auth"
      ]
    },
    "message": "Operation completed for staging environment."
  },
  {
    "id": "00a85473-8242-4912-bda3-c1623a78b64a",
    "timestamp": "2025-12-21T04:19:22.314766+00:00",
    "service": "auth-service",
    "env": "prod",
    "type": "payment",
    "status": "success",
    "severity": 4,
    "source": "us-east-1/instance-8729",
    "metadata": {
      "request_id": "req-5d2d904f",
      "user_id": "usr-7274",
      "region": "us-west-2",
      "retry_count": 0,
      "latency_ms": 903.02,
      "tags": []
    },
    "message": "Operation completed for prod environment."
  },
  {
    "id": "7603c36c-f139-4e3c-8aee-25571f5df912",
    "timestamp": "2025-12-21T06:14:42.314889+00:00",
    "service": "payment-service",
    "env": "prod",
    "type": "job",
    "status": "success",
    "severity": 5,
    "source": "ap-northeast-1/instance-7471",
    "metadata": {
      "request_id": "req-7f0223bc",
      "user_id": "usr-1483",
      "region": "ap-northeast-1",
      "retry_count": 0,
      "latency_ms": 3419.23,
      "tags": [
        "auth",
        "infra",
        "payment"
      ]
    },
    "message": "Operation completed for prod environment."
  },
  {
    "id": "d89a40c0-e87d-4c78-a7c4-21c740497b71",
    "timestamp": "2025-12-21T06:17:31.312088+00:00",
    "service": "auth-service",
    "env": "staging",
    "type": "network",
    "status": "success",
    "severity": 3,
    "source": "eu-central-1/instance-1722",
    "metadata": {
      "request_id": "req-00e85ece",
      "user_id": "usr-6464",
      "region": "us-west-2",
      "retry_count": 0,
      "latency_ms": 3189.2,
      "tags": [
        "batch",
        "edge"
      ]
    },
    "message": "Operation failed for staging environment."
  },
  {
    "id": "d7c524a5-5304-417f-af42-e12f3838b326",
    "timestamp": "2025-12-21T07:47:20.311881+00:00",
    "service": "payment-service",
    "env": "prod",
    "type": "auth",
    "status": "success",
    "severity": 3,
    "source": "eu-central-1/instance-7572",
    "metadata": {
      "request_id": "req-448aaa9e",
      "user_id": "usr-2084",
      "region": "us-west-2",
      "retry_count": 0,
      "latency_ms": 4566.55,
      "tags": [
        "batch",
        "critical"
      ]
    },
    "message": "Operation retrying for prod environment."
  },
  {
    "id": "905c7bdd-74f0-4eae-aa59-43ce836435e3",
    "timestamp": "2025-12-21T08:18:46.314064+00:00",
    "service": "notification-service",
    "env": "staging",
    "type": "network",
    "status": "success",
    "severity": 4,
    "source": "eu-central-1/instance-1356",
    "metadata": {
      "request_id": "req-655ce508",
      "user_id": "usr-5169",
      "region": "us-east-1",
      "retry_count": 0,
      "latency_ms": 3731.56,
      "tags": [
        "auth",
        "edge",
        "payment"
      ]
    },
    "message": "Operation retrying for staging environment."
  },
  {
    "id": "34fa32b6-d043-4e4c-b4e5-0699c8ebe27a",
    "timestamp": "2025-12-21T08:47:06.314565+00:00",
    "service": "notification-service",
    "env": "prod",
    "type": "system",
    "status": "warning",
    "severity": 3,
    "source": "eu-central-1/instance-9827",
    "metadata": {
      "request_id": "req-2b1ac76c",
      "user_id": "usr-6302",
      "region": "eu-central-1",
      "retry_count": 0,
      "latency_ms": 1453.77,
      "tags": [
        "batch",
        "critical",
        "payment"
      ]
    },
